maturity_score_map = {
"There are no processes for Community Growth." : 0,
"Little to no process documentation, -governance, or -ownership for Community Growth. Progress on Community Growth is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Community Growth  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Community Growth are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Community Growth are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Community Growth  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Community Growth." : 0,
"Community members have a weak understanding of how for Community Growth with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Community Growth." : 1,
"Community members have some skills for Community Growth but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Community Growth. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Community Growth . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Community Growth and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Community Growth does not exist." : 0,
"Information to support Community Growth is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Community Growth is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Community Growth is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Community Growth  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Community Growth  is continuously identified and benchmarked." : 5,
"There are no resources available for Community Growth . Inivdiduals who do participate in Community Growth do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Community Growth. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Community Growth, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Community Growth's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Community Growth are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Community Growth. Most work done for Community Growth is compensated." : 4,
"New resources and other innovations that can improve Community Growth are investigated, benchmarked, proven, and deployed. All work done towards Community Growth is compensated." : 5,
"There are no processes for Knowledge Retention." : 0,
"Little to no process documentation, -governance, or -ownership for Knowledge Retention. Progress on Knowledge Retention is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Knowledge Retention  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Knowledge Retention are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Knowledge Retention are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Knowledge Retention  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Knowledge Retention." : 0,
"Community members have a weak understanding of how for Knowledge Retention with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Knowledge Retention." : 1,
"Community members have some skills for Knowledge Retention but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Knowledge Retention. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Knowledge Retention . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Knowledge Retention and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Knowledge Retention does not exist." : 0,
"Information to support Knowledge Retention is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Knowledge Retention is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Knowledge Retention is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Knowledge Retention  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Knowledge Retention  is continuously identified and benchmarked." : 5,
"There are no resources available for Knowledge Retention . Inivdiduals who do participate in Knowledge Retention do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Knowledge Retention. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Knowledge Retention, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Knowledge Retention's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Knowledge Retention are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Knowledge Retention. Most work done for Knowledge Retention is compensated." : 4,
"New resources and other innovations that can improve Knowledge Retention are investigated, benchmarked, proven, and deployed. All work done towards Knowledge Retention is compensated." : 5,
"There are no processes for Diversity of Perspectives." : 0,
"Little to no process documentation, -governance, or -ownership for Diversity of Perspectives. Progress on Diversity of Perspectives is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Diversity of Perspectives  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Diversity of Perspectives are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Diversity of Perspectives are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Diversity of Perspectives  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Diversity of Perspectives." : 0,
"Community members have a weak understanding of how for Diversity of Perspectives with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Diversity of Perspectives." : 1,
"Community members have some skills for Diversity of Perspectives but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Diversity of Perspectives. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Diversity of Perspectives . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Diversity of Perspectives and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Diversity of Perspectives does not exist." : 0,
"Information to support Diversity of Perspectives is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Diversity of Perspectives is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Diversity of Perspectives is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Diversity of Perspectives  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Diversity of Perspectives  is continuously identified and benchmarked." : 5,
"There are no resources available for Diversity of Perspectives . Inivdiduals who do participate in Diversity of Perspectives do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Diversity of Perspectives. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Diversity of Perspectives, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Diversity of Perspectives's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Diversity of Perspectives are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Diversity of Perspectives. Most work done for Diversity of Perspectives is compensated." : 4,
"New resources and other innovations that can improve Diversity of Perspectives are investigated, benchmarked, proven, and deployed. All work done towards Diversity of Perspectives is compensated." : 5,
"There are no processes for Integration Profile Establishment." : 0,
"Little to no process documentation, -governance, or -ownership for Integration Profile Establishment. Progress on Integration Profile Establishment is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Integration Profile Establishment  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Integration Profile Establishment are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Integration Profile Establishment are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Integration Profile Establishment  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Integration Profile Establishment." : 0,
"Community members have a weak understanding of how for Integration Profile Establishment with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Integration Profile Establishment." : 1,
"Community members have some skills for Integration Profile Establishment but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Integration Profile Establishment. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Integration Profile Establishment . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Integration Profile Establishment and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Integration Profile Establishment does not exist." : 0,
"Information to support Integration Profile Establishment is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Integration Profile Establishment is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Integration Profile Establishment is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Integration Profile Establishment  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Integration Profile Establishment  is continuously identified and benchmarked." : 5,
"There are no resources available for Integration Profile Establishment . Inivdiduals who do participate in Integration Profile Establishment do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Integration Profile Establishment. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Integration Profile Establishment, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Integration Profile Establishment's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Integration Profile Establishment are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Integration Profile Establishment. Most work done for Integration Profile Establishment is compensated." : 4,
"New resources and other innovations that can improve Integration Profile Establishment are investigated, benchmarked, proven, and deployed. All work done towards Integration Profile Establishment is compensated." : 5,
"There are no processes for Standardization." : 0,
"Little to no process documentation, -governance, or -ownership for Standardization. Progress on Standardization is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Standardization  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Standardization are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Standardization are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Standardization  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Standardization." : 0,
"Community members have a weak understanding of how for Standardization with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Standardization." : 1,
"Community members have some skills for Standardization but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Standardization. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Standardization . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Standardization and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Standardization does not exist." : 0,
"Information to support Standardization is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Standardization is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Standardization is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Standardization  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Standardization  is continuously identified and benchmarked." : 5,
"There are no resources available for Standardization . Inivdiduals who do participate in Standardization do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Standardization. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Standardization, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Standardization's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Standardization are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Standardization. Most work done for Standardization is compensated." : 4,
"New resources and other innovations that can improve Standardization are investigated, benchmarked, proven, and deployed. All work done towards Standardization is compensated." : 5,
"There are no processes for Compliance Testing." : 0,
"Little to no process documentation, -governance, or -ownership for Compliance Testing. Progress on Compliance Testing is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Compliance Testing  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Compliance Testing are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Compliance Testing are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Compliance Testing  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Compliance Testing." : 0,
"Community members have a weak understanding of how for Compliance Testing with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Compliance Testing." : 1,
"Community members have some skills for Compliance Testing but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Compliance Testing. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Compliance Testing . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Compliance Testing and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Compliance Testing does not exist." : 0,
"Information to support Compliance Testing is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Compliance Testing is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Compliance Testing is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Compliance Testing  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Compliance Testing  is continuously identified and benchmarked." : 5,
"There are no resources available for Compliance Testing . Inivdiduals who do participate in Compliance Testing do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Compliance Testing. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Compliance Testing, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Compliance Testing's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Compliance Testing are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Compliance Testing. Most work done for Compliance Testing is compensated." : 4,
"New resources and other innovations that can improve Compliance Testing are investigated, benchmarked, proven, and deployed. All work done towards Compliance Testing is compensated." : 5,
"There are no processes for User Base Growth." : 0,
"Little to no process documentation, -governance, or -ownership for User Base Growth. Progress on User Base Growth is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for User Base Growth  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for User Base Growth are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for User Base Growth are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for User Base Growth  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for User Base Growth." : 0,
"Community members have a weak understanding of how for User Base Growth with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for User Base Growth." : 1,
"Community members have some skills for User Base Growth but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help User Base Growth. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for User Base Growth . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of User Base Growth and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support User Base Growth does not exist." : 0,
"Information to support User Base Growth is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support User Base Growth is available in silos, hard to locate for others." : 2,
"Information governance defines how information for User Base Growth is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for User Base Growth  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for User Base Growth  is continuously identified and benchmarked." : 5,
"There are no resources available for User Base Growth . Inivdiduals who do participate in User Base Growth do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for User Base Growth. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for User Base Growth, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"User Base Growth's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for User Base Growth are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  User Base Growth. Most work done for User Base Growth is compensated." : 4,
"New resources and other innovations that can improve User Base Growth are investigated, benchmarked, proven, and deployed. All work done towards User Base Growth is compensated." : 5,
"There are no processes for Operational Alignment." : 0,
"Little to no process documentation, -governance, or -ownership for Operational Alignment. Progress on Operational Alignment is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Operational Alignment  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Operational Alignment are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Operational Alignment are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Operational Alignment  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Operational Alignment." : 0,
"Community members have a weak understanding of how for Operational Alignment with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Operational Alignment." : 1,
"Community members have some skills for Operational Alignment but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Operational Alignment. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Operational Alignment . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Operational Alignment and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Operational Alignment does not exist." : 0,
"Information to support Operational Alignment is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Operational Alignment is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Operational Alignment is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Operational Alignment  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Operational Alignment  is continuously identified and benchmarked." : 5,
"There are no resources available for Operational Alignment . Inivdiduals who do participate in Operational Alignment do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Operational Alignment. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Operational Alignment, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Operational Alignment's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Operational Alignment are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Operational Alignment. Most work done for Operational Alignment is compensated." : 4,
"New resources and other innovations that can improve Operational Alignment are investigated, benchmarked, proven, and deployed. All work done towards Operational Alignment is compensated." : 5,
"There are no processes for Tool, Product and Reference Implementation Development." : 0,
"Little to no process documentation, -governance, or -ownership for Tool, Product and Reference Implementation Development. Progress on Tool, Product and Reference Implementation Development is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Tool, Product and Reference Implementation Development  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Tool, Product and Reference Implementation Development are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Tool, Product and Reference Implementation Development are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Tool, Product and Reference Implementation Development  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Tool, Product and Reference Implementation Development." : 0,
"Community members have a weak understanding of how for Tool, Product and Reference Implementation Development with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Tool, Product and Reference Implementation Development." : 1,
"Community members have some skills for Tool, Product and Reference Implementation Development but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Tool, Product and Reference Implementation Development. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Tool, Product and Reference Implementation Development . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Tool, Product and Reference Implementation Development and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Tool, Product and Reference Implementation Development does not exist." : 0,
"Information to support Tool, Product and Reference Implementation Development is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Tool, Product and Reference Implementation Development is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Tool, Product and Reference Implementation Development is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Tool, Product and Reference Implementation Development  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Tool, Product and Reference Implementation Development  is continuously identified and benchmarked." : 5,
"There are no resources available for Tool, Product and Reference Implementation Development . Inivdiduals who do participate in Tool, Product and Reference Implementation Development do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Tool, Product and Reference Implementation Development. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Tool, Product and Reference Implementation Development, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Tool, Product and Reference Implementation Development's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Tool, Product and Reference Implementation Development are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Tool, Product and Reference Implementation Development. Most work done for Tool, Product and Reference Implementation Development is compensated." : 4,
"New resources and other innovations that can improve Tool, Product and Reference Implementation Development are investigated, benchmarked, proven, and deployed. All work done towards Tool, Product and Reference Implementation Development is compensated." : 5,
"There are no processes for Market Creation." : 0,
"Little to no process documentation, -governance, or -ownership for Market Creation. Progress on Market Creation is based on individual’s knowledge, manual interventions and with unpredictable results." : 1,
"Key processes for Market Creation  are identified and documented locally. Responsibilities and handoff are poorly understood, and results are inconsistent." : 2,
"Key processes for Market Creation are documented community wide, ownership is defined, and handoff points established. There is inconsistent adoption, execution, and results." : 3,
"Processes for Market Creation are defined, understood, reliable, standardized, efficient, measured and adopted community wide with consistent results." : 4,
"Processes for Market Creation  are continuously reviewed, benchmarked and improved resulting in industry-leading practices and results." : 5,
"There is no organization for Market Creation." : 0,
"Community members have a weak understanding of how for Market Creation with limited skills, training, and poorly defined roles. The community has not allocated community members/working groups for Market Creation." : 1,
"Community members have some skills for Market Creation but may be lacking experience or training. Inconsistent roles and responsibilities." : 2,
"Community members have good skills, experience and available training is in place to help Market Creation. Roles and responsibilities are defined and assigned to members/working groups." : 3,
"Community members have clear roles and responsibilities, have suitable training and are adequately staffed for Market Creation . Members proactively identify people and organizational improvements and have succession plans in place." : 4,
"Community members have an expert and deeply contextualized understanding of Market Creation and are working in a culture that supports and actively embraces continuous improvement, benchmarking and innovation." : 5,
"Data/information to support Market Creation does not exist." : 0,
"Information to support Market Creation is unavailable, unknown, incomplete, incorrect, inconsistent, and not exploited. Minimal descriptive reporting and analytics are performed manually, not used for decision making." : 1,
"Information to support Market Creation is available in silos, hard to locate for others." : 2,
"Information governance defines how information for Market Creation is collected, stored, understood, accessed, owned, and deleted." : 3,
"Information for Market Creation  is available and well understood across the community and externally. Information quality is measured and corrected." : 4,
"New information for Market Creation  is continuously identified and benchmarked." : 5,
"There are no resources available for Market Creation . Inivdiduals who do participate in Market Creation do so voluntarily in their own time." : 0,
"Few, if any,  resources, including budget, are assigned for Market Creation. Some participating individuals receive resources from the organizations they represent." : 1,
"Some  resources are identified for Market Creation, but additional requirements are not part of investment decisions. Some participating individuals receive resources from the organizations they represent." : 2,
"Market Creation's relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Market Creation are compensated for their effort by the organization they represent." : 3,
"New resources are made available to increase the maturity of  Market Creation. Most work done for Market Creation is compensated." : 4,
"New resources and other innovations that can improve Market Creation are investigated, benchmarked, proven, and deployed. All work done towards Market Creation is compensated." : 5,

    # hack job, don't remove
    "Diversity of Perspectives' relationship to resources is defined and requirements are part of the investment planning process. Most individuals performing work for Diversity of Perspectives are compensated for their effort by the organization they represent." : 3,
    "There are no resources available for Community Growth . Individuals who do participate in Community Growth do so voluntarily in their own time.\n" : 0,
    "Information to support Intergration Profile Establishment is available in silos, hard to locate for others." : 2,
    "Information governance defines how information for Intergration Profile Establishment is collected, stored, understood, accessed, owned, and deleted." : 3,

}